name: ETL Pipeline

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight UTC
  workflow_dispatch:      # manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests.py

      - name: Run ETL pipeline
        run: |
          python extract.py
          python -c "import extract, transform, load; data=extract.extract(); clean_df, agg_df=transform.transform(data); load.load(clean_df, agg_df)"
          
      - name: Upload results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: etl-results
          path: |
            clean_data.csv
            agg_data.csv
