name: ETL_Pipeline

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  validation_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run validation tests
        run: python tests.py

      - name: Run ETL pipeline
        run: |
          python extract.py
          python -c "import extract, transform, load; data=extract.extract(); clean_df, agg_df=transform.transform(data); load.load(clean_df, agg_df)"
